apiVersion: v1
kind: Service
metadata:
  name: customerserviceservice
spec:
  type: NodePort
  selector:
    app: customerservice
  ports:
    - protocol: TCP
      nodePort: 30085
      port: 9003
      targetPort: 9003